### ISSUE TITLE
🧪 🐞 💥  Build Error From Card Test Coverage `Snap Shot`

### ISSUE THREAD

**Issue by LowLifeArcade** [margaritahumanitarian/helpafamily#368]
**What happened?**

We get this build error in our CI/CD running the github test coverage report.

```
Run yarn test:coverage
yarn run v1.22.17
$ yarn jest --coverage
$ /home/runner/work/helpafamily/helpafamily/node_modules/.bin/jest --coverage
PASS __tests__/components/MainDonationForm.spec.js
FAIL components/Card/card.spec.js
  ● Test Card component › should have snapshot

    expect(received).toMatchSnapshot()

    Snapshot name: `Test Card component should have snapshot 1`

    - Snapshot  - 1
    + Received  + 1

    @@ -1,8 +1,8 @@
      <div>
        <div
    -     class="jsx-2132092508 group card flex rounded-md overflow-hidden ml-8 duration-500 z-10 md:hover:scale-110"
    +     class="jsx-2132092508 group card flex rounded-md overflow-hidden ml-8 duration-500 z-10 md:hover:scale-110 md:shadow-md md:hover:shadow-lg"
        >
          <figure
            class="jsx-2132092508"
          >
            <span

      32 |     const { container } = renderComp(cardData);
      33 |
    > 3[4](https://github.com/margaritahumanitarian/helpafamily/runs/5524105362?check_suite_focus=true#step:5:4) |     expect(container).toMatchSnapshot();
         |                       ^
      3[5](https://github.com/margaritahumanitarian/helpafamily/runs/5524105362?check_suite_focus=true#step:5:5) |   });
      3[6](https://github.com/margaritahumanitarian/helpafamily/runs/5524105362?check_suite_focus=true#step:5:6) |   it('should display correctly', () => {
      3[7](https://github.com/margaritahumanitarian/helpafamily/runs/5524105362?check_suite_focus=true#step:5:7) |     const { container, getByText } = renderComp(cardData);

      at Object.<anonymous> (components/Card/card.spec.js:34:23)

 › 1 snapshot failed.
PASS __tests__/components/MainDonationFormInNeed.spec.js
PASS components/Astronaut/astronaut.spec.js
  ● Console

    console.warn
      Warning: componentWillUpdate has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.
      
      * Move data fetching code or side effects to componentDidUpdate.
      * Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 1[8](https://github.com/margaritahumanitarian/helpafamily/runs/5524105362?check_suite_focus=true#step:5:8).x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
      
      Please update the following components: Lottie

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:67:30)
      at warn (node_modules/react-dom/cjs/react-dom.development.js:34:5)
      at Object.<anonymous>.ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings (node_modules/react-dom/cjs/react-dom.development.js:11536:7)
      at flushRenderPhaseStrictModeWarningsInDEV (node_modules/react-dom/cjs/react-dom.development.js:23822:31)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:23005:3)
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:468:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11276:10)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:22[9](https://github.com/margaritahumanitarian/helpafamily/runs/5524105362?check_suite_focus=true#step:5:9)90:3)

---------------------------------|---------|----------|---------|---------|-------------------
File                             | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
---------------------------------|---------|----------|---------|---------|-------------------
All files                        |   23.27 |    23.55 |   18.78 |   23.16 |                   
 components                      |   36.21 |    18.18 |   23.88 |   35.91 |                   
  CardsLayout.js                 |       0 |        0 |       0 |       0 | 7-[10](https://github.com/margaritahumanitarian/helpafamily/runs/5524105362?check_suite_focus=true#step:5:10)              
  DoctorsAsVolunteersCard.js     |       0 |      100 |       0 |       0 | 6                 
  ElectronicsDropOffCard.js      |       0 |      100 |       0 |       0 | 6                 
  FallPreventionForEldersCard.js |       0 |      100 |       0 |       0 | 6-17              
  FoodDistributionSupportCard.js |       0 |      100 |       0 |       0 | 6-17              
  Footer.js                      |       0 |        0 |       0 |       0 | 6-23              
  HealthWorkshopCard.js          |       0 |      100 |       0 |       0 | 6-17              
  HeroSection.js                 |       0 |        0 |       0 |       0 | 7                 
  HotMealDayCard.js              |       0 |      100 |       0 |       0 | 6-17              
  HotMealDaySection.js           |       0 |        0 |       0 |       0 | 9-18              
  HumanitarianClinicCard.js      |       0 |      100 |       0 |       0 | 6-17              
  HygieneKitsCard.js             |       0 |      100 |       0 |       0 | 6                 
  LandingPageNav.js              |       0 |        0 |       0 |       0 | 17-22             
  LaptopForFamiliesCard.js       |       0 |      100 |       0 |       0 | 6                 
  LargeHeroContent.js            |       0 |        0 |       0 |       0 | 22-45             
  LargeHeroSection.js            |       0 |        0 |       0 |       0 | 19-31             
  LargeInfoSection.js            |       0 |        0 |       0 |       0 | 8-31              
  MainDonationForm.js            |   86.36 |    93.33 |   83.33 |    87.8 | 73-74,86-88       
  Modal.js                       |     100 |      100 |     100 |     100 |                   
  Navbar.js                      |       0 |        0 |       0 |       0 | 15-37             
  PrimaryLayout.js               |       0 |        0 |       0 |       0 | 16-35             
  SVGBackgrounds.js              |       0 |        0 |       0 |       0 | 5-92              
  SideNavbar.js                  |       0 |        0 |       0 |       0 | 8-88              
  TestimonialCard.js             |       0 |      100 |       0 |       0 | 4-5               
  ThemeContext.js                |   71.87 |       50 |      80 |   71.87 | 19-22,27-32       
 components/Astronaut            |   93.33 |      100 |      80 |   93.33 |                   
  constants.js                   |     100 |      100 |     100 |     100 |                   
  index.js                       |   92.85 |      100 |      80 |   92.85 | 33                
 components/Card                 |    92.3 |      100 |   88.88 |    92.3 |                   
  index.js                       |    92.3 |      100 |   88.88 |    92.3 | 151               
 components/email                |       0 |        0 |       0 |       0 |                   
  EmailCapture.js                |       0 |      100 |       0 |       0 | 8-53              
  EmailCaptureHelper.js          |       0 |      100 |       0 |       0 | 4                 
  InteractiveSection.js          |       0 |        0 |       0 |       0 | 5-47              
  Questions.js                   |       0 |      100 |       0 |       0 | 9-10              
  SurveyContainer.js             |       0 |        0 |       0 |       0 | 5-6               
  SurveySections.js              |       0 |        0 |       0 |       0 | 7-69              
  Thankyou.js                    |       0 |      100 |       0 |       0 | 5-20              
  ThankyouEmail.js               |       0 |        0 |       0 |       0 | 6-16              
 components/form                 |   52.94 |    29.41 |   55.55 |   53.84 |                   
  CheckboxFormControl.js         |     100 |      100 |     100 |     100 |                   
  InputFormControl.js            |       0 |        0 |       0 |       0 | 17-48             
  SelectFormControl.js           |     100 |       50 |     100 |     100 | 9                 
  TextareaFormControl.js         |       0 |        0 |       0 |       0 | 5-26              
 hooks                           |    8.82 |        0 |    5.26 |    9.09 |                   
  useIntersectionObserver.js     |       0 |        0 |       0 |       0 | 3-51              
  usePosition.js                 |       0 |        0 |       0 |       0 | 4-73              
  useStripeSession.js            |   54.54 |      100 |      50 |   54.54 | [11](https://github.com/margaritahumanitarian/helpafamily/runs/5524105362?check_suite_focus=true#step:5:11)-27             
 pages                           |       0 |        0 |       0 |       0 |                   
  404.js                         |       0 |      100 |       0 |       0 | 7                 
  _app.js                        |       0 |      100 |       0 |       0 | 8-15              
  _document.js                   |       0 |      100 |       0 |       0 | 8-13              
  electronics-gifting-cities.js  |       0 |        0 |       0 |       0 | 13-58             
  fund.js                        |       0 |      100 |       0 |       0 | [12](https://github.com/margaritahumanitarian/helpafamily/runs/5524105362?check_suite_focus=true#step:5:12)-101            
  give-devices.js                |       0 |        0 |       0 |       0 | 12-91             
  give-your-time.js              |       0 |      100 |       0 |       0 | 9-[13](https://github.com/margaritahumanitarian/helpafamily/runs/5524105362?check_suite_focus=true#step:5:13)              
  in-kind.js                     |       0 |      100 |       0 |       0 | 9-13              
  index.js                       |       0 |      100 |       0 |       0 | 16-34             
  landing-page.js                |       0 |      100 |       0 |       0 | 26-95             
  partner-with-us.js             |       0 |      100 |       0 |       0 | 12-89             
  thank-you.js                   |       0 |      100 |       0 |       0 | 7                 
---------------------------------|---------|----------|---------|---------|-------------------

Snapshot Summary
 › 1 snapshot failed from 1 test suite. Inspect your code changes or run `yarn run jest -u` to update them.

Test Suites: 1 failed, 3 passed, 4 total
Tests:       1 failed, [14](https://github.com/margaritahumanitarian/helpafamily/runs/5524105362?check_suite_focus=true#step:5:14) passed, [15](https://github.com/margaritahumanitarian/helpafamily/runs/5524105362?check_suite_focus=true#step:5:15) total
Snapshots:   1 failed, 1 total
Time:        5.7[64](https://github.com/margaritahumanitarian/helpafamily/runs/5524105362?check_suite_focus=true#step:5:64) s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

**Steps to reproduce**
1. Unfortunately you won't see this error as it's only viewable by maintainers, but you may be able to reproduce it locally. 

**What did you expect to happen?**
Build should complete to run Test Coverage report

**Comment by LowLifeArcade** [comment]
@idiglove perhaps you can help here!

**Comment by LowLifeArcade** [comment]
I remade the sanpshot and that seemed to work. Though it generates random css classes so not sure if this will stay working.

**Comment by idiglove** [comment]
Hmm, yarn test -- -u, should make it work. I wonder what the random css classes are

**Comment by LowLifeArcade** [comment]
> I wonder what the random css classes are

I believe that is what tailwind does when it renders.

**Comment by LowLifeArcade** [comment]
It seems to be working. I'll reopen this issue if we have the problem pop back up.
